name: Testing deploy as it should be done :)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@10.0
        with:
          cli: 1.11.1.1165

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ hashFiles('deps.edn') }}

      - name: Build application
        run: clojure -T:build uber

      - name: Persist revision
        run: git rev-parse --short HEAD > target/.rev

      - name: Copy JAR to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "target/legomenon-*,target/.rev"
          target: "dist"
          strip_components: 1
