name: Testing deploy as it should be done :)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@10.0
        with:
          cli: 1.10.1.693

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ hashFiles('deps.edn') }}

      # - name: Test clojure execution
      #   run: clojure -e "(+ 1 1)"

      - name: Echo current directory
        run: pwd

      - name: Display current directory contnet
        run: ls -al

      # - name: Build application
      #   run: clojure -T:build uber

      # - name: Check build :)
      #   run: ls target

      # - name: Copy JAR to the server


      # - name: Restart the app
